/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    Card: typeof import('./src/components/ui/card/Card.vue')['default']
    CardContent: typeof import('./src/components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./src/components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./src/components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./src/components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./src/components/ui/card/CardTitle.vue')['default']
    Carousel: typeof import('./src/components/ui/carousel/Carousel.vue')['default']
    CarouselContent: typeof import('./src/components/ui/carousel/CarouselContent.vue')['default']
    CarouselItem: typeof import('./src/components/ui/carousel/CarouselItem.vue')['default']
    CarouselNext: typeof import('./src/components/ui/carousel/CarouselNext.vue')['default']
    CarouselPrevious: typeof import('./src/components/ui/carousel/CarouselPrevious.vue')['default']
    FormControl: typeof import('./src/components/ui/form/FormControl.vue')['default']
    FormDescription: typeof import('./src/components/ui/form/FormDescription.vue')['default']
    FormItem: typeof import('./src/components/ui/form/FormItem.vue')['default']
    FormLabel: typeof import('./src/components/ui/form/FormLabel.vue')['default']
    FormMessage: typeof import('./src/components/ui/form/FormMessage.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    Input: typeof import('./src/components/ui/input/Input.vue')['default']
    Label: typeof import('./src/components/ui/label/Label.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slider: typeof import('./src/components/ui/slider/Slider.vue')['default']
    Table: typeof import('./src/components/ui/table/Table.vue')['default']
    TableBody: typeof import('./src/components/ui/table/TableBody.vue')['default']
    TableCaption: typeof import('./src/components/ui/table/TableCaption.vue')['default']
    TableCell: typeof import('./src/components/ui/table/TableCell.vue')['default']
    TableEmpty: typeof import('./src/components/ui/table/TableEmpty.vue')['default']
    TableFooter: typeof import('./src/components/ui/table/TableFooter.vue')['default']
    TableHead: typeof import('./src/components/ui/table/TableHead.vue')['default']
    TableHeader: typeof import('./src/components/ui/table/TableHeader.vue')['default']
    TableRow: typeof import('./src/components/ui/table/TableRow.vue')['default']
    Toast: typeof import('./src/components/ui/toast/Toast.vue')['default']
    ToastAction: typeof import('./src/components/ui/toast/ToastAction.vue')['default']
    ToastClose: typeof import('./src/components/ui/toast/ToastClose.vue')['default']
    ToastDescription: typeof import('./src/components/ui/toast/ToastDescription.vue')['default']
    Toaster: typeof import('./src/components/ui/toast/Toaster.vue')['default']
    ToastProvider: typeof import('./src/components/ui/toast/ToastProvider.vue')['default']
    ToastTitle: typeof import('./src/components/ui/toast/ToastTitle.vue')['default']
    ToastViewport: typeof import('./src/components/ui/toast/ToastViewport.vue')['default']
  }
}
